### ISSUE TITLE
Instructions for version 1 seem to be confusing some people

### ISSUE THREAD

**Issue by nicolasmccurdy** [paircolumbus/FindTheAnagrams#15]
I'm starting to see a pattern where final answers for this challenge look like the code below. Note that I replaced real solutions with calls to a fake method named `example_method()` to hopefully remove spoilers from this issue.

```ruby
# Version 1
def detect_anagram(word1, word2)
  canonical(word1) == canonical(word2)
  example_method(word1) == example_method(word2)
end

# Version 2
def canonical(word) 
  example_method(word)
end

# ...
```

I hope it's clear, but what seems to be happening is that people leave their version 1 solutions in when they complete version 2. Should we try to make it more clear that you only need `canonical(word1) == canonical(word2)` in the version 1 method when you're submitting? If so, how?

**Comment by degoeym** [comment]
I definltely think it should be made more clear, though I think the people who've been running into this problem are fairly new to programming in general, so the concepts of OOP may not be entirely clear to them.

Two things I can add from when I did the exercise:

1) The method name of "canonical" doesn't make it very clear as to what it's supposed to actually *do*. I was confused for a moment, but given I know what a method is supposed to do as far as OOP concepts are concerned, I picked up on the fact that I was supposed to pass in the word and then do my sorting, downcasing, and all that jazz on it, and do it as part of a comparison.

2) The instructions for this should also be included in the readme file and not just the ruby file itself.

I'd almost suggest going as far as not even including the method "skeleton" in the code, and instead simply note that they can achieve code nivrana by taking what they've done twice in the detect_anagram method, and extrapolating it to its own method so it's only done once in the code instead of twice, thus intorducing them to refactoring, or "DRYing" out their code.

**Comment by nicolasmccurdy** [comment]
I :100:% agree.

**Comment by degoeym** [comment]
Came up with a quick solution. Let me know what you guys think. Feel free to make changes.

**Comment by nicolasmccurdy** [comment]
:+1: I really like that you mentioned DRY. My only concern is if how to extract a function that is called twice would be clear enough.

**Comment by nicolasmccurdy** [comment]
CC @J3RN

**Comment by nicolasmccurdy** [comment]
By the way @degoeym, @J3RN though it might simplify things (and make this less confusing) if we reduce the exercise to only filling in the canonical method. I'm going to make a pull request for it soon.
